[2025-04-13T18:54:37.044+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [queued]>
[2025-04-13T18:54:37.053+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [queued]>
[2025-04-13T18:54:37.054+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 4
[2025-04-13T18:54:37.066+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): aggregate_search_volume> on 2025-04-13 17:00:00+00:00
[2025-04-13T18:54:37.070+0000] {standard_task_runner.py:57} INFO - Started process 195 to run task
[2025-04-13T18:54:37.073+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'daily_search_volume_aggregation', 'aggregate_search_volume', 'scheduled__2025-04-13T17:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/daily_search_volume_aggregation.py', '--cfg-path', '/tmp/tmpdd4cj5tw']
[2025-04-13T18:54:37.075+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask aggregate_search_volume
[2025-04-13T18:54:37.138+0000] {task_command.py:415} INFO - Running <TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [running]> on host def22a2c4662
[2025-04-13T18:54:37.213+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_search_volume_aggregation' AIRFLOW_CTX_TASK_ID='aggregate_search_volume' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T17:00:00+00:00'
[2025-04-13T18:54:37.223+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-13T18:54:37.224+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py
[2025-04-13T18:54:40.664+0000] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-04-13T18:54:40.665+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-04-13T18:54:40.665+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-04-13T18:54:40.665+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-04-13T18:54:40.665+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-04-13T18:54:40.666+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-04-13T18:54:40.666+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-04-13T18:54:40.666+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-04-13T18:54:40.666+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-04-13T18:54:40.666+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-04-13T18:54:40.667+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-04-13T18:54:40.686+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.
[2025-04-13T18:54:40.690+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_search_volume_aggregation, task_id=aggregate_search_volume, execution_date=20250413T170000, start_date=20250413T185437, end_date=20250413T185440
[2025-04-13T18:54:40.700+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task aggregate_search_volume (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.; 195)
[2025-04-13T18:54:40.720+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-13T18:54:40.736+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
