[2025-04-13T18:17:21.880+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [queued]>
[2025-04-13T18:17:21.885+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [queued]>
[2025-04-13T18:17:21.885+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-04-13T18:17:21.891+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): aggregate_search_volume> on 2025-04-13 17:00:00+00:00
[2025-04-13T18:17:21.894+0000] {standard_task_runner.py:57} INFO - Started process 326 to run task
[2025-04-13T18:17:21.895+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'daily_search_volume_aggregation', 'aggregate_search_volume', 'scheduled__2025-04-13T17:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/daily_search_volume_aggregation.py', '--cfg-path', '/tmp/tmpug01szla']
[2025-04-13T18:17:21.897+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask aggregate_search_volume
[2025-04-13T18:17:21.935+0000] {task_command.py:415} INFO - Running <TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:00:00+00:00 [running]> on host 254b97b44857
[2025-04-13T18:17:21.980+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_search_volume_aggregation' AIRFLOW_CTX_TASK_ID='aggregate_search_volume' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T17:00:00+00:00'
[2025-04-13T18:17:21.987+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-13T18:17:21.987+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py
[2025-04-13T18:17:22.050+0000] {spark_submit.py:491} INFO - /home/airflow/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory
[2025-04-13T18:17:22.050+0000] {spark_submit.py:491} INFO - /home/airflow/.local/lib/python3.8/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-04-13T18:17:22.059+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.
[2025-04-13T18:17:22.062+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=daily_search_volume_aggregation, task_id=aggregate_search_volume, execution_date=20250413T170000, start_date=20250413T181721, end_date=20250413T181722
[2025-04-13T18:17:22.068+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task aggregate_search_volume (Cannot execute: spark-submit --master yarn --conf spark.master=local[*] --conf spark.app.name=daily_search_volume_aggregation --conf spark.driver.memory=1g --conf spark.executor.memory=1g --name arrow-spark --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.; 326)
[2025-04-13T18:17:22.077+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-13T18:17:22.088+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
