[2025-04-13T19:00:56.597+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:01:00+00:00 [queued]>
[2025-04-13T19:00:56.605+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:01:00+00:00 [queued]>
[2025-04-13T19:00:56.606+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-04-13T19:00:56.619+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): aggregate_search_volume> on 2025-04-13 17:01:00+00:00
[2025-04-13T19:00:56.623+0000] {standard_task_runner.py:57} INFO - Started process 404 to run task
[2025-04-13T19:00:56.627+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'daily_search_volume_aggregation', 'aggregate_search_volume', 'scheduled__2025-04-13T17:01:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/daily_search_volume_aggregation.py', '--cfg-path', '/tmp/tmpv8gvg6e6']
[2025-04-13T19:00:56.630+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask aggregate_search_volume
[2025-04-13T19:00:56.745+0000] {task_command.py:415} INFO - Running <TaskInstance: daily_search_volume_aggregation.aggregate_search_volume scheduled__2025-04-13T17:01:00+00:00 [running]> on host def22a2c4662
[2025-04-13T19:00:56.823+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='daily_search_volume_aggregation' AIRFLOW_CTX_TASK_ID='aggregate_search_volume' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T17:01:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T17:01:00+00:00'
[2025-04-13T19:00:56.832+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2025-04-13T19:00:56.833+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.master=local[*] --name arrow-spark --verbose --queue root.default /opt/airflow/dags/spark/daily_aggregation.py
[2025-04-13T19:00:59.887+0000] {spark_submit.py:491} INFO - Using properties file: null
[2025-04-13T19:01:00.048+0000] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-04-13T19:01:00.049+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-04-13T19:01:00.049+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-04-13T19:01:00.049+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-04-13T19:01:00.050+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-04-13T19:01:00.050+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-04-13T19:01:00.050+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-04-13T19:01:00.050+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-04-13T19:01:00.051+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-04-13T19:01:00.051+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-04-13T19:01:00.051+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-04-13T19:01:00.087+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.master=local[*] --name arrow-spark --verbose --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.
[2025-04-13T19:01:00.091+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_search_volume_aggregation, task_id=aggregate_search_volume, execution_date=20250413T170100, start_date=20250413T190056, end_date=20250413T190100
[2025-04-13T19:01:00.100+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task aggregate_search_volume (Cannot execute: spark-submit --master yarn --conf spark.driver.memory=1g --conf spark.executor.memory=1g --conf spark.master=local[*] --name arrow-spark --verbose --queue root.default /opt/airflow/dags/spark/daily_aggregation.py. Error code is: 1.; 404)
[2025-04-13T19:01:00.144+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-13T19:01:00.162+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
